const navbarLinks = [
  { title: 'Home', id: 'home', href: '/' },
  { title: 'Boots', id: 'boots', href: '/shopping' },
 
  { title: 'About', id: 'about', href: '/about' },
  { title: 'Contact', id: 'contact', href: '/contact' },
];

const AllBoots = [
  {
    id: 1,
    name: 'Adidas Predator 25 Elite',
    image: '/assets/MenuImages/Adidas Predator 25 Elite.png',
    title: 'Total Control. Total Power.',
    price: '$430',
    description:
      'A modern Predator built for precision and dominance, featuring Strikeskin zones and a bold red design inspired by the 1998 classic.',
  },
  {
    id: 2,
    name: 'Adidas F50 Elite',
    image: '/assets/MenuImages/Adidas F50 Elite.png',
    title: 'Born For Pure Speed.',
    price: '$260',
    description:
      'Lightweight speed boot with Sprintweb technology and Aerocage structure, designed for explosive acceleration.',
  },
  {
    id: 3,
    name: 'Adidas Copa Pure 3 Elite',
    image: '/assets/MenuImages/Adidas Copa Pure 3 Elite.png',
    title: 'Touch That Tells Stories.',
    price: '$199',
    description:
      'Premium leather boot offering a soft, natural touch and a classic feel reimagined for the modern game.',
  },
  {
    id: 4,
    name: 'Adidas Predator 25 Road to Glory',
    image: '/assets/MenuImages/Adidas Predator 25 Road to Glory.png',
    title: 'Glory Awaits The Bold.',
    price: '$200',
    description:
      'Limited edition Predator with a white, black, and gold finish, built for football’s biggest stages.',
  },
  {
    id: 5,
    name: 'Adidas F50 Road to Glory',
    image: '/assets/MenuImages/Adidas F50 Road to Glory.png',
    title: 'Sprint Into History.',
    price: '$160',
    description:
      'Elite speed boot with a premium gold-accent design, created for championship-level performance.',
  },
  {
    id: 6,
    name: 'Adidas Predator 25 Radiant Blaze',
    image: '/assets/MenuImages/Adidas Predator 25 Radiant Blaze.png',
    title: 'Electric. Relentless. Unstoppable.',
    price: '$260',
    description:
      'Eye-catching gradient design with high-performance control technology for the new season.',
  },
];

const reviews = [
  {
    id: 1,
    name: 'Javier M.',
    role: 'Pro Midfielder',
    country: 'Spin',
    flag: 'es',
    rating: 5,
    bootImage: '/assets/MenuImages/Adidas Copa Pure 3 Elite.png',
    quote:
      "Fastest boot I've ever worn. First touch on the ball felt like an extension of my foot.",
    detail:
      'The Sprintweb upper is insane — light, locked in, no hot spots. Wore them in a Champions League qualifier and felt zero fatigue.',
    avatar: 'JM',

    color: '#FF2D00',
  },
  {
    id: 2,
    name: 'Lena K.',
    role: 'Winger · Bundesliga',
    country: 'Germany',
    flag: 'de',
    rating: 5,
    bootImage: '/assets/MenuImages/Adidas F50 Elite.png',
    quote: 'Control like nothing else. Every deadball situation feels engineered for me.',
    detail:
      'Strikeskin zones give insane grip on the ball. Tried four boots this season — Predator 25 stays on.',
    avatar: 'LK',
    color: '#d4a017',
  },
  {
    id: 3,
    name: 'Rahul S.',
    role: 'Striker · ISL',
    country: 'India',
    flag: 'in',
    rating: 5,
    bootImage: '/assets/MenuImages/Adidas F50 Road to Glory.png',
    quote: "Wearing Messi's boot changed how I attack the ball. Pure confidence.",
    detail:
      'The fit is insanely snug, the sole is so responsive. Scored a hat-trick in my debut with these.',
    avatar: 'RS',
    color: '#FF2D00',
  },
  {
    id: 4,
    name: 'Marcus T.',
    role: 'Centre-back · MLS',
    country: ' USA',
    flag: 'us',
    rating: 4,
    bootImage: '/assets/MenuImages/Adidas F50 Road to Glory.png',
    quote: 'Old-school leather feel, new-gen performance. Defenders need touch too.',
    detail:
      'Soft kangaroo leather upper feels premium. Perfect for long passing range. Took one game to break in.',
    avatar: 'MT',
    color: '#d4a017',
  },
  {
    id: 5,
    name: 'Yuki T.',
    role: 'Playmaker · J-League',
    country: ' Japan',
    flag: 'jp',
    rating: 5,
    bootImage: '/assets/MenuImages/Adidas Predator 25 Elite.png',
    quote: 'Every pass has purpose. The grip zones feel like cheating — in the best way.',
    detail: 'I play a lot of tight spaces, and the Predator 25 gives me confidence in every touch.',
    avatar: 'YT',
    color: '#FF2D00',
  },
  {
    id: 6,
    name: 'Amara D.',
    role: 'Winger · AFCON',
    country: ' Ivory Coast',
    flag: 'ci',
    rating: 5,
    bootImage: '/assets/MenuImages/Adidas Predator 25 Radiant Blaze.png',
    quote: 'Wore these in the final. Scored the winner. Enough said.',
    detail:
      "Gold colorway, gold moment. The limited edition Road to Glory pack is a collector's dream that actually performs.",
    avatar: 'AD',
    color: '#d4a017',
  },
  {
    id: 7,
    name: 'Carlos R.',
    role: 'Full-back · La Liga B',
    country: ' Brazil',
    flag: 'br',
    rating: 5,
    bootImage: '/assets/MenuImages/Adidas Predator 25 Road to Glory.png',
    quote: "Lamine Yamal's boot on my feet? The pace is real.",
    detail: 'Rose laces are fire. The Aerocage keeps my foot locked even in wet conditions.',
    avatar: 'CR',
    color: '#FF2D00',
  },
  {
    id: 8,
    name: 'Sofia B.',
    role: 'Attacking Mid · WSL',
    country: ' Sweden',
    flag: 'se',
    rating: 5,
    bootImage: '/assets/MenuImages/Adidas F50 Road to Glory.png',
    quote: 'I never want another boot. Copa Pure is timeless.',
    detail:
      'As a technical player, touch is everything. The leather upper gives me feedback no synthetic boot can.',
    avatar: 'SB',
    color: '#d4a017',
  },
];
const products = [
  {
    id: 1,
    name: 'F50 Elite',
    collection: 'Pure Victory Pack',
    category: 'Speed',
    price: 280,
    originalPrice: 280,
    surface: ['FG', 'AG'],
    sizes: [6, 7, 7.5, 8, 8.5, 9, 9.5, 10, 11],
    color: 'Solar Yellow',
    colorHex: '#FFD600',
    badge: 'New',
    rating: 4.9,
    reviews: 312,
    img: '/assets/ShopImages/boot-1.png',
    wornBy: 'Lamine Yamal',
  },
  {
    id: 2,
    name: 'Predator 25 Elite',
    collection: 'Pure Victory Pack',
    category: 'Control',
    price: 300,
    originalPrice: 300,
    surface: ['FG', 'AG'],
    sizes: [6, 7, 8, 8.5, 9, 9.5, 10, 11, 12],
    color: 'Lucid Red',
    colorHex: '#FF2D00',
    badge: 'New',
    rating: 4.8,
    reviews: 276,
    img: '/assets/ShopImages/boot-2.png',
    wornBy: 'Jude Bellingham',
  },
  {
    id: 3,
    name: 'Copa Pure 3 Elite',
    collection: 'Pure Victory Pack',
    category: 'Touch',
    price: 260,
    originalPrice: 320,
    surface: ['FG', 'AG'],
    sizes: [7, 7.5, 8, 8.5, 9, 9.5, 10, 11],
    color: 'Cloud White',
    colorHex: '#F5F5F5',
    badge: 'Sale',
    rating: 4.7,
    reviews: 198,
    img: '/assets/ShopImages/boot-3.png',
    wornBy: 'Thomas Müller',
  },
  {
    id: 4,
    name: 'F50 Road to Glory',
    collection: 'Road to Glory',
    category: 'Speed',
    price: 300,
    originalPrice: 300,
    surface: ['FG'],
    sizes: [7, 8, 8.5, 9, 9.5, 10, 11],
    color: 'Metallic Gold',
    colorHex: '#d4a017',
    badge: 'Limited',
    rating: 5.0,
    reviews: 89,
    img: '/assets/ShopImages/boot-4.png',
    wornBy: 'UCL Final',
  },
  {
    id: 5,
    name: "Predator 25 'Radiant Blaze'",
    collection: 'Radiant Blaze',
    category: 'Control',
    price: 310,
    originalPrice: 310,
    surface: ['FG', 'AG'],
    sizes: [6, 7, 8, 9, 9.5, 10, 11, 12],
    color: 'Lucid Lemon',
    colorHex: '#E8FF00',
    badge: 'New',
    rating: 4.9,
    reviews: 142,
    img: '/assets/ShopImages/boot-5.png',
    wornBy: 'Pedri',
  },
  {
    id: 6,
    name: "F50 Messi 'La Vida'",
    collection: 'Messi Spring Pack',
    category: 'Speed',
    price: 290,
    originalPrice: 290,
    surface: ['FG', 'AG'],
    sizes: [7, 7.5, 8, 8.5, 9, 9.5, 10],
    color: 'Miami Pastel',
    colorHex: '#FF6BB0',
    badge: 'Signature',
    rating: 4.9,
    reviews: 445,
    img: '/assets/ShopImages/boot-6.png',
    wornBy: 'Lionel Messi',
  },
  {
    id: 7,
    name: 'Copa Pure 3 FG',
    collection: 'Core',
    category: 'Touch',
    price: 160,
    originalPrice: 200,
    surface: ['FG'],
    sizes: [6, 7, 8, 8.5, 9, 10, 11, 12],
    color: 'Core Black',
    colorHex: '#1a1a1a',
    badge: 'Sale',
    rating: 4.5,
    reviews: 562,
    img: '/assets/ShopImages/boot-7.png',
    wornBy: null,
  },
  {
    id: 8,
    name: 'F50 League FG',
    collection: 'Core',
    category: 'Speed',
    price: 100,
    originalPrice: 100,
    surface: ['FG', 'MG'],
    sizes: [6, 7, 8, 9, 10, 11, 12],
    color: 'Core White',
    colorHex: '#ECECEC',
    badge: null,
    rating: 4.3,
    reviews: 834,
    img: '/assets/ShopImages/boot-8.png',
    wornBy: null,
  },
  {
    id: 9,
    name: 'Predator League FG',
    collection: 'Core',
    category: 'Control',
    price: 90,
    originalPrice: 90,
    surface: ['FG', 'AG'],
    sizes: [5, 6, 7, 8, 9, 10, 11, 12],
    color: 'Impact Orange',
    colorHex: '#FF6B35',
    badge: null,
    rating: 4.4,
    reviews: 721,
    img: '/assets/ShopImages/boot-9.png',
    wornBy: null,
  },
  {
    id: 10,
    name: 'F50 Heartbreaker',
    collection: 'Yamal Series',
    category: 'Speed',
    price: 285,
    originalPrice: 285,
    surface: ['FG', 'AG'],
    sizes: [6, 7, 8, 8.5, 9, 9.5, 10],
    color: 'Rose Pink',
    colorHex: '#FF6BB0',
    badge: 'Signature',
    rating: 5.0,
    reviews: 201,
    img: '/assets/ShopImages/boot-10.png',
    wornBy: 'Lamine Yamal',
  },
  {
    id: 11,
    name: 'Predator 94 Reverse',
    collection: 'Archive Revival',
    category: 'Heritage',
    price: 260,
    originalPrice: 260,
    surface: ['FG'],
    sizes: [7, 8, 8.5, 9, 9.5, 10, 11],
    color: 'Vintage White',
    colorHex: '#F0EDE0',
    badge: 'Heritage',
    rating: 4.8,
    reviews: 156,
    img: '/assets/ShopImages/boot-11.png',
    wornBy: null,
  },
  {
    id: 12,
    name: 'Copa Pure 3 AG',
    collection: 'Core',
    category: 'Touch',
    price: 180,
    originalPrice: 220,
    surface: ['AG'],
    sizes: [6, 7, 8, 9, 10, 11],
    color: 'Lucid Blue',
    colorHex: '#3B82F6',
    badge: 'Sale',
    rating: 4.6,
    reviews: 289,
    img: '/assets/ShopImages/boot-12.png',
    wornBy: null,
  },
];
export { navbarLinks, AllBoots, reviews, products };
