import { Geist, Geist_Mono, Bebas_Neue, Poppins } from 'next/font/google'; // 👈 Add Poppins
import './globals.css';
import Navbar from '@/Components/Navbar';
import Footer from '@/Components/Footer';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const bebasNeue = Bebas_Neue({
  variable: '--font-bebas-neue',
  subsets: ['latin'],
  weight: '400',
});

const poppins = Poppins({
  variable: '--font-poppins', // 👈 CSS variable
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'], // 👈 Pick weights you need
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${bebasNeue.variable} ${poppins.variable} h-full antialiased`}
      // 👆 Add poppins.variable here
    >
      <body className="min-h-full flex flex-col">
      <Navbar />
        {children}

        <Footer />
      </body>
    </html>
  );
}
